deals-top-stats
mabbus/enablement-api pull request #102
Opened 2020-12-29 15:19 UTC by mabbus

2020-12-30 16:23 UTC, lexod requested changes

2020-12-30 16:23 UTC, lexod commented on app/Http/Controllers/Web/EmployeesDealsController.php
> +        $payback = $deals->get()->sum(function ($item) {
Choose only deals columns which you actually need
Same for #63

2020-12-30 16:23 UTC, lexod commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +        $deals = $this->syndicate->load('deals')->deals;
Choose only deals columns which you actually need

2020-12-30 16:23 UTC, lexod commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +        $transactions = Transaction::where('type', Transaction::TYPE_SYNDICATE_CREDIT)
Choose only deals columns which you actually need

2020-12-30 16:23 UTC, lexod commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +        $netCollected = $transactions->get()->sum('amount');
Just ->sum() will do just fine

2021-01-04 23:02 UTC, mabbus commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +        $netCollected = $transactions->get()->sum('amount');
It breaks when I remove get()

2021-01-04 23:04 UTC, mabbus commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +        $transactions = Transaction::where('type', Transaction::TYPE_SYNDICATE_CREDIT)
why? i need to sum up transactions?

2021-01-05 00:21 UTC, lexod commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +        $transactions = Transaction::where('type', Transaction::TYPE_SYNDICATE_CREDIT)
Why do you need created_at/updated_at for example? All you need are id, type, amount and deal_id

2021-01-05 00:27 UTC, lexod requested changes

2021-01-05 00:27 UTC, lexod commented on app/Http/Tasks/Syndicate/GetTopSyndicateStats.php
> +            return $carry = $carry + $item->pivot->amount;
You don't need carry assignment in any of these rows. Just return carry + YOUR EXPRESSION

2021-01-06 19:58 UTC, lexod requested changes

2021-01-06 19:58 UTC, lexod commented on app/Http/Controllers/Web/EmployeesDealsController.php
> +        $rate = $payback / $amount;
0 division exception if $amount === 0

2021-01-06 19:58 UTC, lexod commented on app/Http/Controllers/Web/EmployeesDealsController.php
> +            'payment' => $deals->get()->sum(function($item) {
duplicate query. create a collection you will be applying sums to
same for 64

2021-01-07 15:13 UTC, lexod approved these changes

2021-01-07 15:20 UTC, closed without merging