Override Payments
mabbus/enablement-api pull request #74
Opened 2020-10-13 20:08 UTC by mabbus

2020-10-20 16:05 UTC, lexod requested changes

2020-10-20 16:05 UTC, lexod commented on app/Http/Requests/Deal/AttachOverride.php
> +            'amount' => 'numeric|required',
specify min/max and total amount of digits after coma

2020-10-20 16:05 UTC, lexod commented on app/Http/Tasks/Transactions/Deal/ChargeMerchant.php
> +            ->whereDate('start_at','<=', Carbon::today()->toDateString())
```php
->whereDate('start_at','<=', Carbon::today()->startOfDay())
->whereDate('end_at', '>=', Carbon::today()->endOfDay())
```

2020-10-21 19:42 UTC, mabbus commented on app/Http/Requests/Deal/AttachOverride.php
> +            'amount' => 'numeric|required',
on amount?

2020-10-22 14:52 UTC, lexod commented on app/Http/Requests/Deal/AttachOverride.php
> +            'amount' => 'numeric|required',
yes

2020-10-23 06:54 UTC, merged