product-type
mabbus/enablement-api pull request #79
Opened 2020-10-27 21:46 UTC by mabbus

2020-10-28 00:44 UTC, lexod requested changes

2020-10-28 00:44 UTC, lexod commented on app/Http/Controllers/Web/EmployeesDealsController.php
> +        if($request->query('product_type')) {
should come from request->validated()

2020-10-28 00:44 UTC, lexod commented on app/Http/Requests/Deal/CreateDeal.php
> +            'product_type_id' => 'required|integer',
add exists check

2020-10-28 00:44 UTC, lexod commented on app/Http/Tasks/ProductType/GetProductTypes.php
> +        return ProductType::all();
this place is a potential performance issue
1. select only those columns you need
1. restrict it 5 items
1. you don't need a task for such a simple action

2020-10-28 00:44 UTC, lexod commented on app/Http/Tasks/Deal/AdminGetDeals.php
> +        if(Arr::has($data, 'product_type')) {
```php
$deals->when(Arr::has($data, 'product_type'), function($query) use ($data) {return $query->where('product_type_id', $data['product_type']);});
```

2020-10-28 00:44 UTC, lexod commented on app/Http/Traits/ValidationTrait.php
> +            'product_type' => 'nullable|integer|min:1'
not meant to be here,
needs to be a part of each request.

2020-10-28 00:44 UTC, lexod commented on database/migrations/2020_10_26_132118_create_deal_product_type_table.php
> +            $table->string('name', 200)->nullable();
what's the point to have it nullable?

2020-11-02 22:59 UTC, mabbus commented on app/Http/Tasks/ProductType/GetProductTypes.php
> +        return ProductType::all();
we eventually need to filter by company_id and stuff

2020-11-02 23:41 UTC, lexod requested changes

2020-11-02 23:41 UTC, lexod commented on app/Http/Controllers/Web/EmployeesDealsController.php
> +
user `->when()`

2020-11-02 23:41 UTC, lexod commented on app/Http/Controllers/Web/EmployeesDealsController.php
> +            if(Arr::get($data, 'product_type')) {
user `->when()`

2020-11-02 23:41 UTC, lexod commented on app/Http/Tasks/Deal/AdminGetDeals.php
> +
user `->when()`

2020-11-06 17:50 UTC, lexod approved these changes

2020-11-06 17:50 UTC, merged