Multiple Merchants for Syndicates
mabbus/enablement-api pull request #87
Opened 2020-11-14 02:35 UTC by mabbus

- synd cant log in anymore
- login for synd/merchants
- add business role on attach merchant to business

2020-11-18 18:18 UTC, lexod requested changes

2020-11-18 18:18 UTC, lexod commented on app/Deal.php
> +        if ($this->startDate === 0){
there is already a fix for it
https://github.com/mabbus/enablement-api/pull/88/files#diff-5f2b341af34f0cda1e17893bbbd53dbb9986a11e758fb5869c53c65a26c26316R426

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Business/AddMerchantToBusinessTask.php
> +    public function __construct(Model $entity, array $data, $role = false )
should be `public function __construct(Model $entity, array $data, Role $role = null )`

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Business/AddMerchantToBusinessTask.php
> +        $this->entity = $entity;
needs a check for types of entity here

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Business/AddMerchantToBusinessTask.php
> +        } catch (\Exception $e) {
should be `\Throwable`

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Business/AddMerchantToBusinessTask.php
> +            return response()->json($e);
task cannot return JSON response it's a responsibility of the Controller.
Throw exception instead.

2020-11-18 18:18 UTC, lexod commented on app/Http/Controllers/Web/SyndicateDealsController.php
> +                'syndicate' => $user->merchant->syndicate->first()
use $user->load()

2020-11-18 18:18 UTC, lexod commented on app/Http/Controllers/Web/SyndicateDealsController.php
> +        $syndDeal = (new SyndicateGetDeal($deal, $user->merchant->syndicate->first()))->run();
this line duplicates line 52

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Business/AddMerchantToBusinessTask.php
> +            $merchant = Merchant::find($this->data['merchant_id']);
use firstOrFail() if merchant doesn't exist

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Syndicate/CreateSyndicate.php
> +            $user = new User($this->data);
get rid of the comments.
we have git for it

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Syndicate/CreateSyndicate.php
> +        DB::beginTransaction();
it's a single table.
no need for transactions

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Syndicate/CreateSyndicateTask.php
> +        //$syndicate->user()->associate($this->account);
get rid of the comments.
we have git for it

2020-11-18 18:18 UTC, lexod commented on app/Http/Tasks/Syndicate/CreateSyndicate.php
>  class CreateSyndicate implements TaskInterface
what is the difference between this task and `app/Http/Tasks/Syndicate/CreateSyndicateTask.php` ?

2020-11-18 18:18 UTC, lexod commented on app/Merchant.php
> +    public function syndicate()
if it belongs to many - should be `syndicates`

2020-11-18 18:18 UTC, lexod commented on database/migrations/2020_08_05_195543_create_roles_table.php
> +            \App\Role::BUSINESS
very bad idea to edit old migrations
create a new one instead.
don't forget to update existing roles and users mappings

2020-11-18 18:18 UTC, lexod commented on app/Role.php
> +    const BUSINESS = 'business';
sync up users, roles and mapping table

2020-11-18 18:18 UTC, lexod commented on resources/views/employees/syndicates/show.blade.php
> +                merchant_id: '',
will have to change this whole thing to a component

2020-11-18 18:50 UTC, mabbus commented on app/Deal.php
> +        if ($this->startDate === 0){
this should have been it's own pr then

2020-11-18 18:53 UTC, mabbus commented on app/Http/Tasks/Syndicate/CreateSyndicate.php
>  class CreateSyndicate implements TaskInterface
I think one i used by API and one is used by web

2020-11-18 18:53 UTC, mabbus commented on app/Merchant.php
> +    public function syndicate()
belongs to 1

2020-11-20 15:51 UTC, lexod commented on app/Http/Controllers/Web/EmployeesSyndicatesController.php
> +            'title' => 'Syndicates | ' . $syndicate->business_name,
`"Syndicates |  $syndicate->business_name"`

2020-11-20 16:12 UTC, lexod approved these changes

2020-11-20 16:14 UTC, merged