nov-ui-fixes
mabbus/enablement-api pull request #91
Opened 2020-12-01 21:43 UTC by mabbus

2020-12-01 21:55 UTC, lexod requested changes

2020-12-01 21:55 UTC, lexod commented on app/Role.php
> +        return parent::where('name', self::MERCHANT)->first();
what's the point to duplicate?

2020-12-01 21:55 UTC, lexod commented on database/migrations/2020_09_29_202533_create_deal_has_override.php
> +            $table->dateTime('start_at');
this migration is on prod already. Make a new one.
Don't forget down method

2020-12-01 21:55 UTC, lexod commented on resources/views/employees/settings/view.blade.php
> +                        'Content-Type': 'application/json', 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
you don't need these values.
neither on 106

2020-12-02 06:07 UTC, lexod requested changes

2020-12-02 06:07 UTC, lexod commented on database/migrations/2020_12_01_200643_update_deal_has_override_times.php
> +        //
add down method

2020-12-02 06:07 UTC, lexod commented on resources/views/employees/advances/show.blade.php
> +                                            <td>{{str_replace('_', ' ', \Illuminate\Support\Str::title($transaction->type))}}</td>
add attribute to Transaction model

2020-12-02 06:07 UTC, lexod commented on resources/views/employees/settings/view.blade.php
> +                        'Content-Type': 'application/json', 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
Remove this function

2020-12-02 06:07 UTC, lexod commented on resources/views/syndicates/advances/show.blade.php
> +                                                        <td>{{str_replace('_', ' ', \Illuminate\Support\Str::title($transaction->type))}}</td>
Add attribute to transaction model

2020-12-02 06:07 UTC, lexod commented on resources/views/syndicates/advances/show.blade.php
> +                                                        <td>{{($transaction->internal_status === 'settled') ? $transaction->updated_at : ''}}</td>
compare with constant to avoid raw string

2020-12-02 16:28 UTC, mabbus commented on resources/views/employees/advances/show.blade.php
> +                                            <td>{{str_replace('_', ' ', \Illuminate\Support\Str::title($transaction->type))}}</td>
We sholud have a Helper function for this because we use it in more than one place

2020-12-02 21:56 UTC, lexod approved these changes

2020-12-02 21:56 UTC, lexod commented on app/Transaction.php
> +use phpDocumentor\Reflection\Types\This;
remove it

2020-12-02 21:58 UTC, merged